services:
  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todoapp
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    image: todoapp:latest
    container_name: myapp
    restart: always
    ports:
      - "80:8000"
    depends_on:
      - db
    env_file:
      - .env.production

volumes:
  mysql_data:
