[app]
# Manual inventory for app instances after `terraform apply`.
# Add one IP per running app instance.
43.205.213.188 ansible_user=ubuntu

[jenkins]
# Add Jenkins server instance IP here.
# Example:
# 3.110.10.20 ansible_user=ubuntu
43.205.213.188 ansible_user=ubuntu
